services:
  tarabbit-server:
    image: python:3.9-slim-buster
    container_name: tarabbit-server
    restart: always
    volumes:
      - ${tarabbit_server_path}:/app
    command: sh -c "cd /app && ls -la && pwd && pip install -r ./requirements.txt && python app/main.py"
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    environment:
      ENCRYPTED_API_KEY: ${ENCRYPTED_API_KEY}
      SECRET_KEY: ${SECRET_KEY}
      MONGO_URI: ${MONGO_URI}

  tarabbit_bot:
    image: python:3.9-slim-buster
    container_name: tarabbit-bot
    restart: always
    volumes:
      - ${tarabbit_bot_path}:/app
    command: sh -c "cd /app && ls -la && pip install -r ./requirements.txt && python app/main.py"
    ports:
      - "25001:25001"
    depends_on:
      - mongodb
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}

  mongodb:
    image: mongo:latest
    container_name: mongodb-tarabbit
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "37027:27017"

  tarot_webapp:
    image: node:latest
    container_name: tarot_webapp
    restart: always
    volumes:
      - /tarabbit/webapp/:/app/
    command: sh -c "cd /app/ && npm run build && npm run preview"
    #command: sh -c "cd /app/ && npm run dev"
    ports:
      - 31313:5173
  # tarabbit_bot:
  #   image: nikolaik/python-nodejs:latest
  #   container_name: tarabbit_bot
  #   restart: always
  #   volumes:
  #     - tarabbit-server/:/main/
  #   command: sh -c "cd /main/ && pip install -r ./requirements.txt && npx nodemon bot.py"
  #   #command: sh -c "cd /main/ && pip install -r ./requirements.txt && python -m main"
  #   #command: sh -c "cd /main/ && pip install -r ./requirements.txt && uvicorn main:app --reload --port 25000"
  #   ports:
  #     - "25001:25001"
  #   logging:
  #     options:
  #       max-size: "12m"
  #       max-file: "5"
  #     driver: json-file

volumes:
  mongodb_data: